'use strict'

export const REQUEST_MESSAGE = 'CHAT_REQUEST_MESSAGE'
export const RECEIVED_MESSAGE = 'CHAT_RECEIVED_MESSAGE'
export const MESSAGE_ERROR='CHAT_MESSAGE_ERROR'


export const REQUEST_REDIS='CHAT_REQUEST_REDIS'
export const RECEIVED_REDIS = 'CHAT_RECEIVED_REDIS'
export const REDIS_ERROR='CHAT_REDIS_ERROR'

export const SEND_BACK = 'MESSAGE_SEND_BACK'