'use strict'

export const REQUEST_DATA = 'RESEARCH_REQUEST_DATA'
export const RECEIVED_DATA = 'RESEARCH_RECEIVED_DATA'
export const ERROR = 'RESEARCH_ERROR'

export const REQUEST_PERIOD = 'RESEARCH_REQUEST_PERIOD'
export const RECEIVED_PERIOD = 'RESEARCH_RECEIVED_PERIOD'